### ISSUE TITLE
Close button no longer works after FF 38.0 update

### ISSUE THREAD

**Issue by IamLosted** [seleznev/firefox-extension-htitle#64] opened 2015-05-21 10:11 UTC
Close button does not work with HTitle 3.4 (just no action) after the recent update to FF 38.0. I use Linux Mint with Cinnamon 2.4.8.

**Comment by seleznev** [comment] 2015-05-21 15:45
It's duplicate of #63

**Closed** 2015-05-21 15:45 UTC
Labels: Duplicate, Invalid
